export const FORGOT_PASSWORD_REQUEST_INITIATED = 'FORGOT_PASSWORD_REQUEST_INITIATED',
    FORGOT_PASSWORD_REQUEST_SUCCEEDED = 'FORGOT_PASSWORD_REQUEST_SUCCEEDED',
    FORGOT_PASSWORD_REQUEST_FAILED = 'FORGOT_PASSWORD_REQUEST_FAILED';