export const UPDATE_ERROR = 'UPDATE_ERROR',
    UPDATE_LOGIN_STATUS = 'UPDATE_LOGIN_STATUS',
    UPDATE_EMAIL = 'UPDATE_EMAIL',
    UPDATE_PASSWORD = 'UPDATE_PASSWORD',
    TOGGLE_PASSWORD_VISIBILITY = 'TOGGLE_PASSWORD_VISIBILITY',
    UPDATE_INPUT_TYPE = 'UPDATE_INPUT_TYPE',
    UPDATE_LOADING = 'UPDATE_LOADING';