export const SWITCH_VIEW = 'SWITCH_VIEW',
    SUBMIT_CANDIDATE = 'SUBMIT_CANDIDATE',
    UPLOAD_FILE = 'UPLOAD_FILE',
    TABLE_VALID = 'TABLE_VALID',
    CLEAR_TABLE = 'CLEAR_TABLE',
    ID_VALID = 'ID_VALID',
    EMAIL_VALID = 'EMAIL_VALID',
    FILE_SIZE = 'FILE_SIZE';