export const ADD_JOB_PROFILE_CHECK = 'ADD_JOB_PROFILE_CHECK',
    FETCH_CHECKS = 'FETCH_CHECKS',
    TOGGLE_DISPLAY='TOGGLE_DISPLAY',
    ADD_JOB_PROFILE_CHECK_SUCCESS = 'ADD_JOB_PROFILE_CHECK_SUCCESS',
    REMOVE_JOB_PROFILE_CHECK = 'REMOVE_JOB_PROFILE_CHECK',
    REMOVE_JOB_PROFILE_CHECK_SUCCESS = 'REMOVE_JOB_PROFILE_CHECK_SUCCESS';