export const CHANGE_DIGIT_1 = 'CHANGE_DIGIT_1',
    CHANGE_DIGIT_2 = 'CHANGE_DIGIT_2',
    CHANGE_DIGIT_3 = 'CHANGE_DIGIT_3',
    CHANGE_DIGIT_4 = 'CHANGE_DIGIT_4',
    CHANGE_DIGIT_5 = 'CHANGE_DIGIT_5',
    RESEND_OTP = 'RESEND_OTP',
    SUBMIT_OTP = 'SUBMIT_OTP',
    ASSIGN_USER = 'ASSIGN_USER';