export const FETCH_JOB_PROFILES = 'FETCH_JOB_PROFILES',
    FETCH_ALL_CHECKS = 'FETCH_ALL_CHECKS',
    UPDATE_DISPLAY = 'UPDATE_DISPLAY',
    UPDATE_CODE = 'UPDATE_CODE',
    UPDATE_SELECTED_CHECKS = 'UPDATE_SELECTED_CHECKS',
    UPDATE_SELECTED_PROFILE = 'UPDATE_SELECTED_PROFILE',
    TOGGLE_DISPLAY='TOGGLE_DISPLAY';