export const UPDATE_PASSWORD = 'UPDATE_PASSWORD',
    UPDATE_CONFIRMED_PASSWORD = 'UPDATE_CONFIRMED_PASSWORD',
    UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE',
    UPDATE_LOADING = 'UPDATE_LOADING',
    UPDATE_PASSWORDS_MATCH = 'UPDATE_PASSWORDS_MATCH',
    UPDATE_PASSWORDS_VALID = 'UPDATE_PASSWORDS_VALID',
    UPDATE_FETCH_ERROR = 'UPDATE_FETCH_ERROR';