export const CHANGE_PASSWORD_REQUEST_INITIATED = 'CHANGE_PASSWORD_REQUEST_INITIATED',
    CHANGE_PASSWORD_REQUEST_SUCCEEDED = 'CHANGE_PASSWORD_REQUEST_SUCCEEDED',
    CHANGE_PASSWORD_REQUEST_FAILED = 'CHANGE_PASSWORD_REQUEST_FAILED';